const CRYPTO_CALCULATION_EVENT = "CRYPTO_CALCULATION_EVENT";
const PROGRESS_CREATED_EVENT = "PROGRESS_CREATED_EVENT";
const PROGRESS_UPDATED_EVENT = "PROGRESS_UPDATED_EVENT";

const HOMESCREEN_OPENED_EVENT = "HOMESCREEN_OPENED_EVENT";
const COINSSCREEN_OPENED_EVENT = "COINSSCREEN_OPENED_EVENT";
const SAVEDSCREEN_OPENED_EVENT = "SAVEDSCREEN_OPENED_EVENT";
const HISTORYSCREEN_OPENED_EVENT = "HISTORYSCREEN_OPENED_EVENT";
const PROGRESSSCREEN_OPENED_EVENT = "PROGRESS_SCREEN_OPENED_EVENT";
const PROGRESS_DETAILED_SCREEN_OPENED_EVENT =
    "PROGRESS_DETAILED_SCREEN_OPENED_EVENT";

const SAVED_CALCULATION_EVENT = "SAVED_CALCULATION_EVENT";
const SHARE_CALCULATION_EVENT = "SAVED_CALCULATION_EVENT";
const APP_NOT_OPENED_EVENT = "APP_NOT_OPENED_EVENT";

const COIN_DETAILS_TAPPED_EVENT = "COIN_DETAILS_TAPPED_EVENT";

const INTERSTITIAL_ADS_OPENED_EVENT = "INTERSTITIAL_ADS_OPENED_EVENT";
const INTERSTITIAL_ADS_FAILED_EVENT = "INTERSTITIAL_ADS_FAILED_EVENT";
