const CRYPTO_CALCULATION_EVENT = "CRYPTO_CALCULATION_EVENT";
const HOMESCREEN_OPENED_EVENT = "HOMESCREEN_OPENED_EVENT";
const SAVEDSCREEN_OPENED_EVENT = "SAVEDSCREEN_OPENED_EVENT";
const SAVED_CALCULATION_EVENT = "SAVED_CALCULATION_EVENT";
const SHARE_CALCULATION_EVENT = "SAVED_CALCULATION_EVENT";
const APP_NOT_OPENED_EVENT = "APP_NOT_OPENED_EVENT";
